version : '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=12345
    depends_on:
      - db

  db:
    image: postgres:15-alpine

    ports:
      - "5433:5432"

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - ./db-data:/var/lib/postgresql/data # Persist database data

#volumes:
#  pgdata_new: # <--- CHANGE #2